using System;
using System.Collections.Generic;
using System.Linq;
using MySql.Data.MySqlClient;
using SDB.Classes.General;

namespace SDB.Classes.User
{
	/// <summary>
	/// A notification is essentially a private message to a user, generated by changes to objects that they subscribe to.
	/// Creating an object (RMA, shipment, ticket) auto-subscribes that user to it.
	/// Modifying an object can auto-subscribe a user to it based on their preference.
	/// </summary>
	public class ClassNotification
	{
		public int ID { get; set; }

		/// <summary>
		/// Can only be NULL when creating a new Notification, which will use the current DateTime.
		/// </summary>
		public DateTime? MessageDate { get; set; }

		public int NotifyUserID { get; set; }
		public int FromUserID { get; set; }

		/// <summary>
		/// Link to subscription, if applicable. Subscription may be missing if unsubscribed, or if notification was generated by an admin.
		/// </summary>
		public int? SubscriptionID { get; set; }

		/// <summary>
		/// Notification has its own ObjectType because notifications may originate from child objects and the link should point to that, if the user doesn't subscribe to the child.
		/// </summary>
		public ClassSubscription.ObjectTypeEnum ObjectType { get; set; }

		/// <summary>
		/// Notification has its own ObjectID because notifications may originate from child objects and the link should point to that, if the user doesn't subscribe to the child.
		/// </summary>
		public int ObjectID { get; set; }

		public string ObjectName { get; set; }

		public string Message { get; set; }

		[UsedImplicitly]
		public string FromUserName { get; private set; }

		[UsedImplicitly]
		public string LinkText
		{
			get
			{
				switch (ObjectType)
				{
					case ClassSubscription.ObjectTypeEnum.Asset:
					case ClassSubscription.ObjectTypeEnum.Market:
					case ClassSubscription.ObjectTypeEnum.Customer:
						return string.Format("{0}: {1}", ObjectType, ObjectName);
					default:
						return string.Format("{0}: {1}", ObjectType, ObjectID);
				}
			}
		}

		/// <summary>
		/// Retrieves all notifications for user with ID <paramref name="userID"/> which have a <see cref="MessageDate"/> that's not in the future.
		/// </summary>
		/// <param name="userID">The user ID that notifications are for.</param>
		/// <param name="includeFuture">If false (default), only notificaions up to the present date are retrieved. If true, includes all notifications regardless of <see cref="MessageDate"/>.</param>
		public static IEnumerable<ClassNotification> GetForUser(int userID, bool includeFuture = false)
		{
			List<ClassNotification> notifications = new List<ClassNotification>();
			using (MySqlConnection conn = ClassDatabase.CreateMySqlConnection())
			{
				conn.Open();
				using (MySqlCommand cmd = conn.CreateCommand())
				{
					cmd.CommandText =
						@"SELECT n.id, n.notify_user, n.from_user, n.msg_datetime, n.subscription_id,
						n.obj_type, n.obj_id, n.obj_name, n.message,
						u.firstname, u.lastname
						FROM user_notifications n
							JOIN users u ON n.from_user = u.userid
						WHERE n.notify_user = @notify_user "
						+ (includeFuture ? string.Empty : @"AND msg_datetime <= NOW()") +
						@"ORDER BY n.msg_datetime ASC;";
					cmd.Parameters.AddWithValue("notify_user", userID);
					using (MySqlDataReader reader = cmd.ExecuteReader())
						while (reader.Read())
						{
							ClassNotification notification = GetFromReader(reader);
							ClassUser fromUser = new ClassUser
								                     {
									                     First = reader.GetDBString("firstname"),
									                     Last = reader.GetDBString("lastname")
								                     };
							notification.ObjectID = reader.GetDBInt("obj_id");
							notification.ObjectType = (ClassSubscription.ObjectTypeEnum)Enum.Parse(typeof (ClassSubscription.ObjectTypeEnum), reader.GetDBString("obj_type"));
							notification.ObjectName = reader.GetDBString_Null("obj_name");
							notification.FromUserName = fromUser.FirstL;
							notifications.Add(notification);
						}
				}
				conn.Close();
			}
			return notifications;
		}

		/// <summary>
		/// Checks whether any notifications exist for user ID <paramref name="userID"/> beyond the specified DateTime <paramref name="lastMessageDate"/> up until present time.
		/// This allows the notifications form to know whether to request all notifications again or not.
		/// </summary>
		public static bool AnyNotificationsSince(DateTime lastMessageDate, int userID)
		{
			int newNotificationQty;
			using (MySqlConnection conn = ClassDatabase.CreateMySqlConnection())
			{
				conn.Open();
				using (MySqlCommand cmd = conn.CreateCommand())
				{
					cmd.CommandText =
						@"SELECT COUNT(id)
						FROM user_notifications
						WHERE notify_user = @notify_user
						AND msg_datetime > @lastMessageDate
						AND msg_datetime <= NOW();";
					cmd.Parameters.AddWithValue("notify_user", userID);
					cmd.Parameters.AddWithValue("lastMessageDate", lastMessageDate);
					newNotificationQty = Convert.ToInt32(cmd.ExecuteScalar());
				}
				conn.Close();
			}
			return newNotificationQty > 0;
		}

		/// <summary>
		/// Gets the number of notifications for the current user NOT including future notifications.
		/// </summary>
		public static int GetNotificationCount_Current()
		{
			int notificationQty;
			using (MySqlConnection conn = ClassDatabase.CreateMySqlConnection())
			{
				conn.Open();
				using (MySqlCommand cmd = conn.CreateCommand())
				{
					cmd.CommandText =
						@"SELECT COUNT(id)
						FROM user_notifications
						WHERE msg_datetime <= NOW()
						AND notify_user = @notify_user;";
					cmd.Parameters.AddWithValue("notify_user", GS.Settings.LoggedOnUser.ID);
					notificationQty = Convert.ToInt32(cmd.ExecuteScalar());
				}
				conn.Close();
			}
			return notificationQty;
		}

		/// <summary>
		/// Gets the number of notifications (including future) for the current user for the specified object.
		/// </summary>
		/// <remarks>Only works with the specific object, but would be nice to include child objects as well.
		/// For example when unsubscribing from a customer, all child objects could be considered in the
		/// notification removal that this method is part of.</remarks>
		public static int GetNotificationCount_All(ClassSubscription.ObjectTypeEnum objectType, int objectID)
		{
			int notificationQty;
			using (MySqlConnection conn = ClassDatabase.CreateMySqlConnection())
			{
				conn.Open();
				using (MySqlCommand cmd = conn.CreateCommand())
				{
					cmd.CommandText =
						@"SELECT COUNT(id)
						FROM user_notifications
						WHERE notify_user = @notify_user
						AND obj_type = @obj_type
						AND obj_id = @obj_id;";
					cmd.Parameters.AddWithValue("notify_user", GS.Settings.LoggedOnUser.ID);
					cmd.Parameters.AddWithValue("obj_type", objectType.ToString());
					cmd.Parameters.AddWithValue("obj_id", objectID);
					notificationQty = Convert.ToInt32(cmd.ExecuteScalar());
				}
				conn.Close();
			}
			return notificationQty;
		}

		/// <summary>
		/// Adds a new <see cref="ClassNotification"/> to the database.
		/// </summary>
		public static void AddNew(ref ClassNotification notification)
		{
			using (MySqlConnection conn = ClassDatabase.CreateMySqlConnection())
			{
				conn.Open();
				using (MySqlCommand cmd = conn.CreateCommand())
				{
					cmd.CommandText =
						@"INSERT INTO user_notifications
							(notify_user, from_user, msg_datetime, subscription_id,
							obj_type, obj_id, obj_name, message)
						VALUES
							(@notify_user, @from_user, COALESCE(@msg_datetime, NOW()), @subscription_id,
							@obj_type, @obj_id, @obj_name, @message);";
					cmd.Parameters.AddWithValue("notify_user", notification.NotifyUserID);
					cmd.Parameters.AddWithValue("from_user", notification.FromUserID);
					cmd.Parameters.AddWithValue("msg_datetime", notification.MessageDate);
					cmd.Parameters.AddWithValue("subscription_id", notification.SubscriptionID);
					cmd.Parameters.AddWithValue("obj_type", notification.ObjectType.ToString());
					cmd.Parameters.AddWithValue("obj_id", notification.ObjectID);
					cmd.Parameters.AddWithValue("obj_name", notification.ObjectName);
					cmd.Parameters.AddWithValue("message", notification.Message);
					ClassDatabase.ConvertAllNullParameters(cmd.Parameters);
					cmd.ExecuteNonQuery();

					cmd.Parameters.Clear();
					cmd.CommandText = @"SELECT @@IDENTITY";
					notification.ID = Convert.ToInt32(cmd.ExecuteScalar());
				}
				conn.Close();
			}
		}

		/// <summary>
		/// Determines the subscribers of the specified object, generates and sends a notification to them.
		/// Checks for subscribers of parent objects also, but will only send one notification for users subscribed to more than one level.
		/// </summary>
		/// <param name="message">The notification message.</param>
		/// <param name="objectType">The object type.</param>
		/// <param name="objectID">The object ID.</param>
		/// <param name="objectName">The object name (i.e. customer, market); null if not applicable.</param>
		/// <param name="notificationDateTime">DateTime stamp for the message. Uses current database time by default.</param>
		/// <returns>The number of notifications sent.</returns>
		public static int SendNotificationsForObject(string message, ClassSubscription.ObjectTypeEnum objectType, int objectID, string objectName = null, DateTime? notificationDateTime = null)
		{
			// Get list of subscribers to the object
			List<ClassSubscription> subs = ClassSubscription.GetByObject(objectType, objectID).ToList();

			// If a user subscribes to a child and a parent, only send one notification
			subs = subs.GroupBy(s => s.UserID).Select(g => g.First()).ToList();

			// Don't send notifications to same user (unless for future notification or in debug mode)
#if !DEBUG
			if (notificationDateTime == null)
				subs = subs.Where(s => s.UserID != GS.Settings.LoggedOnUser.ID).ToList();
#endif

			// Iterate the list and send notifications
			foreach (ClassSubscription sub in subs)
			{
				ClassNotification notification = new ClassNotification
					                                 {
						                                 FromUserID = GS.Settings.LoggedOnUser.ID,
						                                 MessageDate = notificationDateTime,
						                                 Message = message,
						                                 NotifyUserID = sub.UserID,
						                                 SubscriptionID = sub.ID,
						                                 ObjectType = objectType,
						                                 ObjectID = objectID,
						                                 ObjectName = objectName
					                                 };
				AddNew(ref notification);
			}

			return subs.Count;
		}

		/// <summary>
		/// Deletes the specified single <see cref="ClassNotification"/> from the database.
		/// </summary>
		public static void Delete(ClassNotification notification)
		{
			using (MySqlConnection conn = ClassDatabase.CreateMySqlConnection())
			{
				conn.Open();
				using (MySqlCommand cmd = conn.CreateCommand())
				{
					cmd.CommandText =
						@"DELETE FROM user_notifications
						WHERE id = @id;";
					cmd.Parameters.AddWithValue("id", notification.ID);
					cmd.ExecuteNonQuery();
				}
				conn.Close();
			}
		}

		/// <summary>
		/// Deletes all notifications for the specified subscription.
		/// </summary>
		public static void DeleteBySubscription(ClassSubscription subscription)
		{
			using (MySqlConnection conn = ClassDatabase.CreateMySqlConnection())
			{
				conn.Open();
				using (MySqlCommand cmd = conn.CreateCommand())
				{
					cmd.CommandText =
						@"DELETE FROM user_notifications
						WHERE subscription_id = @subscription_id;";
					cmd.Parameters.AddWithValue("subscription_id", subscription.ID);
					cmd.ExecuteNonQuery();
				}
				conn.Close();
			}
		}

		/// <summary>
		/// Deletes all notifications for the specified object for the current user.
		/// </summary>
		public static void DeleteByObjectForUser(ClassSubscription.ObjectTypeEnum objectType, int objectID)
		{
			using (MySqlConnection conn = ClassDatabase.CreateMySqlConnection())
			{
				conn.Open();
				using (MySqlCommand cmd = conn.CreateCommand())
				{
					cmd.CommandText =
						@"DELETE FROM user_notifications
						WHERE obj_type = @obj_type
						AND obj_id = @obj_id
						AND notify_user = @notify_user;";
					cmd.Parameters.AddWithValue("obj_type", objectType.ToString());
					cmd.Parameters.AddWithValue("obj_id", objectID);
					cmd.Parameters.AddWithValue("notify_user", GS.Settings.LoggedOnUser.ID);
					cmd.ExecuteNonQuery();
				}
				conn.Close();
			}
		}

		/// <summary>
		/// Delete all notifications (including future) for the current user.
		/// </summary>
		public static void DeleteAllByUser()
		{
			DeleteAllByUser(GS.Settings.LoggedOnUser.ID);
		}

		/// <summary>
		/// Delete all notifications (including future) for the specified user.
		/// </summary>
		public static void DeleteAllByUser(int userID)
		{
			using (MySqlConnection conn = ClassDatabase.CreateMySqlConnection())
			{
				conn.Open();
				using (MySqlCommand cmd = conn.CreateCommand())
				{
					cmd.CommandText =
						@"DELETE FROM user_notifications
						WHERE notify_user = @notify_user;";
					cmd.Parameters.AddWithValue("notify_user", userID);
					cmd.ExecuteNonQuery();
				}
				conn.Close();
			}
		}

		/// <summary>
		/// Delete all current (NOT future) notifications for the current user. (Mark all read.)
		/// </summary>
		public static void DeleteCurrentByUser()
		{
			DeleteCurrentByUser(GS.Settings.LoggedOnUser.ID);
		}

		/// <summary>
		/// Delete all current (NOT future) notifications for the specified user. (Mark all read.)
		/// </summary>
		public static void DeleteCurrentByUser(int userID)
		{
			using (MySqlConnection conn = ClassDatabase.CreateMySqlConnection())
			{
				conn.Open();
				using (MySqlCommand cmd = conn.CreateCommand())
				{
					cmd.CommandText =
						@"DELETE FROM user_notifications
						WHERE notify_user = @notify_user
						AND msg_datetime <= NOW();";
					cmd.Parameters.AddWithValue("notify_user", userID);
					cmd.ExecuteNonQuery();
				}
				conn.Close();
			}
		}

		/// <summary>
		/// Gets a <see cref="ClassNotification"/> from the <paramref name="reader"/> at its current position.
		/// </summary>
		private static ClassNotification GetFromReader(MySqlDataReader reader)
		{
			return new ClassNotification
			{
				ID = reader.GetDBInt("id"),
				MessageDate = reader.GetDBDateTime("msg_datetime"),
				NotifyUserID = reader.GetDBInt("notify_user"),
				FromUserID = reader.GetDBInt("from_user"),
				SubscriptionID = reader.GetDBInt_Null("subscription_id"),
				Message = reader.GetDBString("message")
			};
		}
	}
}